version: "3"

networks:
  traefik:
    external: true

services:
  app:
    container_name: telegram_app
    build: .
    command: "/scripts/docker/start_dev.sh"
    volumes:
      - ./app:/app
      - ./data/media:/data/media/
      - ./data/log:/data/log/
      - ./requirements.txt:/requirements.txt
      - ./scripts:/scripts
      - static_volume:/data/static/
    depends_on:
      - database
    environment:
      - PYTHONHASHSEED=0
    env_file:
      - ./.env

  revproxy:
    container_name: telegram_revproxy
    image: nginx
    depends_on:
      - app
    volumes:
      - ./nginx/conf-traefik.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - ./data/media:/usr/src/app/media
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.telegram.rule=Host(`telegram.naicasc.com`)
      - traefik.http.routers.telegram.tls=true
      - traefik.http.routers.telegram.tls.certresolver=lets-encrypt
      - "traefik.http.middlewares.telegram.ipwhitelist.sourcerange=10.8.0.0/24"

  database:
    container_name: telegram_database
    image: mysql:8.0
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_db
    env_file:
      - ./.env


volumes:
  static_volume: