version: '3'

services:
  app:
    container_name: telegram_app
    build: .
    command: "/scripts/docker/start_dev.sh"
    volumes:
    - ./requirements.txt:/requirements.txt
    - ./app:/app
    - ./data/media:/data/media/
    - ./data/log:/data/log/
    - ./scripts:/scripts
    - static_volume:/data/static/
    depends_on:
      - database
    environment:
      - PYTHONHASHSEED=0
    env_file:
      - ./.env

  revproxy:
    container_name: revproxy
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - 8000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
      - ./data/media:/usr/src/app/media


  database:
    container_name: telegram_database
    image: mysql:8.0
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_db
    env_file:
      - ./.env

volumes:
  static_volume:
